# Generated by Django 2.1.2 on 2018-10-14 15:53

import apps.courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenum', models.IntegerField()),
                ('semester', apps.courses.models.SemesterField()),
                ('oldpcr_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', apps.courses.models.SemesterField()),
                ('name', models.CharField(max_length=200)),
                ('credits', models.FloatField(null=True)),
                ('description', models.TextField()),
                ('oldpcr_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=80, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=80, null=True)),
                ('pennkey', models.CharField(max_length=80, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
                ('website', models.URLField(null=True)),
                ('oldpcr_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forms_returned', models.IntegerField()),
                ('forms_produced', models.IntegerField()),
                ('form_type', models.IntegerField()),
                ('comments', models.TextField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30)),
                ('score', models.FloatField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sectionnum', models.IntegerField()),
                ('group', models.IntegerField(null=True)),
                ('sectiontype', models.CharField(max_length=3, null=True)),
                ('oldpcr_id', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('instructors', models.ManyToManyField(to='courses.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
        migrations.AddField(
            model_name='course',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseHistory'),
        ),
        migrations.AddField(
            model_name='course',
            name='primary_alias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.Alias'),
        ),
        migrations.AddField(
            model_name='alias',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='alias',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'sectionnum')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewbit',
            unique_together={('review', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('section', 'instructor')},
        ),
    ]
